apiVersion: 1

datasources:
  - name: InfluxDB_K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: timebutler
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: k6-admin-token
    isDefault: true
    editable: true